name: CI

on:
  push:
    tags:
      - '*'

jobs:
  build:
    if: ${{ github.event.schedule }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v12
    - name: Cache nix environment
      run: nix-shell -I nixpkgs=channel:nixos-20.09 --run "exit 0"
    - name: Test code
      run: python ./instafs/instagram.py
      shell: env nix-shell -I nixpkgs=channel:nixos-20.09 --run "bash -e {0}"

  release:
    if: ${{ !github.event.schedule }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create bundle
      id: info
      run: |
        TAGNAME=$(basename ${{ github.ref }})
        mkdir build
        git tag -l --format='%(body)' $TAGNAME > build/body.txt
        echo ::set-output name=title::$(git tag -l --format='%(subject)' $TAGNAME)
    - uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        body_path: build/body.txt
        name: ${{ steps.info.outputs.title }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
